version: '3.8'

services:
  app:
    build: .
    
    container_name: kaychat_app
    ports:
      - "5015:5015"
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped